print "Starting maya loading and fbx conversion \n";
			
if (`file -q -exists "C:/Users/Owner/DOCUME~1/GitHub/AIGE_03/3_10NA~1/Assets/FREE_P~1/MAYAWO~1.MA"`)
{
	file -o "C:/Users/Owner/DOCUME~1/GitHub/AIGE_03/3_10NA~1/Assets/FREE_P~1/MAYAWO~1.MA";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "C:/Users/Owner/DOCUME~1/GitHub/AIGE_03/3_10NA~1/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

system ("del \"C:\\Users\\Owner\\DOCUME~1\\GitHub\\AIGE_03\\3_10NA~1\\Temp\\CommandPipe\"");

$donepipeKill = `fopen "C:/Users/Owner/DOCUME~1/GitHub/AIGE_03/3_10NA~1/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
