print "Starting maya loading and fbx conversion \n";
			
if (`file -q -exists "D:/Users/gmb9280/stupid/3_20VillagerRehaul/Assets/free_pack/maya wolf.ma"`)
{
	file -o "D:/Users/gmb9280/stupid/3_20VillagerRehaul/Assets/free_pack/maya wolf.ma";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "D:/Users/gmb9280/stupid/3_20VillagerRehaul/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

system ("del \"D:\\Users\\gmb9280\\stupid\\3_20VillagerRehaul\\Temp\\CommandPipe\"");

$donepipeKill = `fopen "D:/Users/gmb9280/stupid/3_20VillagerRehaul/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
